AI_PROVIDER = "gemini"

FREE_TIER = True

MAX_FILES_PER_UPLOAD = 3

MAX_FILE_SIZE_MB = 5

MAX_AI_CALLS_PER_DAY = 20

REQUEST_DELAY_SECONDS = 2

ENABLE_IMAGE_COMPRESSION = True

ENABLE_DUPLICATE_DETECTION = False